name: flutter_shared_components
description: "A collection of reusable Flutter widgets and screens designed to be easily integrated into your projects."
version: 0.0.1
homepage: https://github.com/SoloScripted/flutter-shared-components
repository: https://github.com/SoloScripted/flutter-shared-components
publish_to: 'none' # Prevent accidental publishing to pub.dev

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
