name: flutter_shared_components
description: "A collection of reusable Flutter widgets and screens designed to be easily integrated into your projects."
version: 0.0.3
homepage: https://github.com/SoloScripted/flutter-shared-components
repository: https://github.com/SoloScripted/flutter-shared-components
publish_to: 'none' # Prevent accidental publishing to pub.dev

environment:
  sdk: ">=3.4.0 <4.0.0" # Dart SDK for Flutter 3.22.0
  flutter: ">=3.22.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_tracking_transparency: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
